channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  - pytorch=1.12.1
  - cudatoolkit=11.3
  - torchvision
  - transformers
  - datasets

  - pandas

  - rich
  - typer
  - loguru
  - wandb

  - black
  - isort
  - flake8
  - flake8-bugbear
  - mypy
  - ipywidgets
  - pre-commit

  - pip:
    - timm
    - pytorch_lightning>=1.8
    # - colossalai==0.1.11rc3+torch1.12cu11.3 -f https://release.colossalai.org
