[project]
name = "train_vilt_vqa"
description = "train vilt vqa model"
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Dowon", email = "ks2515@naver.com"}
]

[project.urls]
repository = ""

[tool.isort]
profile = "black"
